### ISSUE TITLE
LoadingView attributes

### ISSUE THREAD

**Issue by qstra** [JeasonWong/BezierLoadingView#2]
these attributes not working dude...

```
    lv:lv_duration="10"
    lv:lv_start_color="#688fdb"
    lv:lv_end_color="#fff"
    lv:lv_internal_radius="5dp"
    lv:lv_external_radius="92dp"
```

**Comment by qstra** [comment]
Btw. its working from code except color change.

**Comment by JeasonWong** [comment]
I tried again just now, it worked well.
![Markdown](http://i1.piimg.com/1070/3552155e355f2f21.jpg)
